name: Remote Dispatch Action Initiator
#test
on:
  workflow_dispatch:
  push:
    branches: ["develop"]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Generate dispatch token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.DISPATCH_APP_ID }}
          private-key: ${{ secrets.DISPATCH_APP_PRIVATE_KEY }}
          owner: patternyard
          repositories: |
            PatternYard-Home
            PatternYard-Packager
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2.0.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          event-type: update
          repository: patternyard/PatternYard-Home
      - name: Repository Dispatch2
        uses: peter-evans/repository-dispatch@v2.0.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          event-type: update
          repository: patternyard/PatternYard-Packager
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout
        uses: actions/checkout@v3

      - name: Make docs
        run: |
         npm install
         npm run build
         npm run docs

      - name: Upload built-media
        uses: actions/upload-artifact@v4
        with:
          name: built-media 
          path: media

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './playground'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
